### ISSUE TITLE
Confusion about "running PRS analysis" subsecion in PRSice-2 section

### ISSUE THREAD

**Issue by MapleHe** [choishingwan/PRS-Tutorial#12]
Thank you for the excellent tutorial.

I'm a little confused with the content in the subsection "running PRS analysis" of the section "PRSice-2".

- Section page: <https://choishingwan.github.io/PRS-Tutorial/prsice/#running-prs-analysis>
- Source page: <https://github.com/choishingwan/PRS-Tutorial/blob/master/docs/prsice.md#running-prs-analysis>

Should the first two R scripts generate **EUR.covariate**? Instead of **EUR.cov**.

In addition, the following PRSice-2 commands use **EUR.cov**, should it be **EUR.covariate**?

In the table of parameters, the **value** column of **cov** row  is **EUR.height**. I think it should be **EUR.covariate** (or maybe **EUR.cov**).

**Comment by choishingwan** [comment]
Hi, thanks for reporting. 
I have now fixed the entry accordingly. The update should be up in a day or two
