### ISSUE TITLE
a typo? map <- obj.bigSNP$map[-2]

### ISSUE THREAD

**Issue by XcodeBio** [choishingwan/PRS-Tutorial#14]
Hi Sam,

Thank you very much for the wonderful PRS tutorial. It is very helpful.

I was going through your LDpred-2 tutorial and I there might be a typo in section 3 ("Reformat data in preparation of LDpred2"). 

# extract the SNP information from the genotype
map <- obj.bigSNP$map[-2] 

Should this be:  map <- obj.bigSNP$map[-3]

Thanks

**Comment by choishingwan** [comment]
You are correct. I think there might have been a version change to bigsnpr
which changes some of the data structure. Will try to update this part of
the tutorial now.

**Comment by XcodeBio** [comment]
Thank you!
