### ISSUE TITLE
Lassosum tutorial : Error in validation step

### ISSUE THREAD

**Issue by DM087** [choishingwan/PRS-Tutorial#18]
Hi Sam,

The validation step in your lassosum tutorial throws an error 

target.res <- validate(out, pheno = target.pheno, covar=cov)
Error in setnames(x, value) : 
  Can't assign 475 names to a 1 column data.table

Is it just me encountering this error? I managed to get it worked but would be great if you can update the code.

Best wishes,
Dev

**Comment by choishingwan** [comment]
I did saw that error before yet haven’t found out the root cause. I think for that we need to transform the target.pheno from a data.table object to a data.frame object (which for some reason is removed from this version of our script), will update it once I have time 

 

Sam

**Comment by DM087** [comment]
Great! That was quick!

Best,
Dev

**Comment by DM087** [comment]
Thank you, Sam!

I am following your lassosum tutorial and have a couple of questions

1. I want to merge the out$pgs (output from lassosum.pipeline) to their corresponding FID's in the fam file. Do you think the code below will do it? 
fam <- fread(paste0(bfile, ".fam"))
fam[,ID:=do.call(paste, c(.SD, sep=":")),.SDcols=c(1:2)]
**fam.pgs=cbind(as.data.frame(fam),out$pgs)**

2. I learnt that the lassosum.pipeline can be performed on chromosome separated files (per chromosome) and can be merged using `merge` command.  Can the validate function be performed on chromosome separated .bed files? 

3. PGS calculation in lassosum.pipeline and validate funtion: 
My understandig is that PGS are already calculated when you run lassosum.pipeline function, and then you use validate function on the resulting object (best lassosum predictor indexed by s and lambda). I noticed that both lassosum.pipeline and validate functions calculate PGS in your tutorial. Could you please explain why? Apologies if i misunderstood something here? 

Thank you.
Dev
