### ISSUE TITLE
File hm3_variants.rds removed by privefl

### ISSUE THREAD

**Issue by mathieu-lemire** [choishingwan/PRS-Tutorial#24]
The file hm3_variants.rds you are referring to has been deleted by git user privefl in commit d2246511ff.  You should update your LDPRED-2 doc by pointing to the last commit where it is still available:

https://github.com/privefl/bigsnpr/blob/b366f09c450819589fb7309219cc01b901f3d2be/data-raw/hm3_variants.rds

**Comment by choishingwan** [comment]
Thanks, LDpred2 has updated the path to the file location. We have now updated the tutorial to account for that. Thank you for your report
