### ISSUE TITLE
 subsetting target dataset prior to analysis

### ISSUE THREAD

**Issue by EugeneEA** [choishingwan/PRS-Tutorial#25]
Hi, I have a following question - should'nt I first filter taget dataset by SNP's which are present in base dataset? To later work only with a overlapping subset of SNP's. It seems critical thing to do before prunning.
Best, Eugene

**Comment by choishingwan** [comment]
Prunning is mainly used for QC and PCA calculation. After obtaining the quality control metric, we will use the full data set for the PRS calculation. By that point, we'd actually do the overlap SNPs matching before we do the clumping to maximize the data. Hope this help.

**Comment by EugeneEA** [comment]
Thanks for the fast reply, it indeed helped
