### ISSUE TITLE
Hyperparameter Tuning with QC Tutorial

### ISSUE THREAD

**Issue by jfrank94** [choishingwan/PRS-Tutorial#26]
I'd like to know if there are any acceptable ranges of values for the parameters in the quality control portion. For example, for the standard GWAS QC, you recommend removing any SNPs with MAF of < 1% and INFO > 0.8, but there wasn't a reason nor range of values to remove the SNPs. 

Can you provide any resources and examples of hyperparameter tuning for quality control?

**Comment by choishingwan** [comment]
Usually, you'd want to perform QC based on your data but we rarely test multiple QC parameter. You can definitely try though. Here is a paper on GWAS QC: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3066182/
