### ISSUE TITLE
Hi, I am using the guidelines provided in your tutorial to calculate PGS in my dataset from already published PGS available in the catalogue. while in plink all runs well except for results are written in .*.profile. which I cannot find being created in my directory as described in your tutorial.

### ISSUE THREAD

**Issue by MehreenSoomro** [choishingwan/PRS-Tutorial#34]
Hi,
 I am using the guidelines provided in your tutorial to calculate PGS in my dataset from already published PGS available in the catalogue. while in plink all runs well except for results are written in .*.profile. which I cannot find being created in my directory as described in your tutorial. I will be extremely grateful for any help provided regarding the issue. I have attached the screenshot. 

![1](https://user-images.githubusercontent.com/56646498/147701796-38b21e25-1785-426e-8505-904ecd451866.png)

**Comment by choishingwan** [comment]
plink's score function does not natively support gz files. You can try and
decompress it before sending it to PLINK to run.

gunzip Abraham2.gz

Sam
