### ISSUE TITLE
number of chromosomes in the LDPred-2

### ISSUE THREAD

**Issue by fmadani** [choishingwan/PRS-Tutorial#36]
Hi @privefl,

In the step titled "Calculate the LD matrix", in the chromosome based calculation, the number of chromosomes is considered 22 while there are 23 pairs in human cells. Is it a typo, or there is any other reason for considering 22? Please clarify.

Farshad

**Comment by privefl** [comment]
Sex chromosomes are often not used when making polygenic scores.
