### ISSUE TITLE
LDPred-2 error: N/A values for beta_grid in genomewide scenario

### ISSUE THREAD

**Issue by fmadani** [choishingwan/PRS-Tutorial#38]
Hi @privefl,

I faced an issue where the values of beta_grid are N/A. 
![image](https://user-images.githubusercontent.com/7520134/152410821-24bd618d-f554-4ce6-91f5-385f7bbea93a.png)

Here is the related command line:
beta_grid <- snp_ldpred2_grid(corr, df_beta, grid.param, ncores = NCORES)

I put all the required codes in a text file attached. 
[LDPred-genomewide-grid.txt](https://github.com/choishingwan/PRS-Tutorial/files/7997388/LDPred-genomewide-grid.txt)

 I tested these codes three times, but got the same values (N/A). Also,  I got warning 'stack imbalance' messages like this:

![image](https://user-images.githubusercontent.com/7520134/152410514-4c5924ba-bca4-4971-88b1-51c82ddec1d1.png)

Please review this issue and let me know what causes it.

Regards,
Farshad

**Comment by choishingwan** [comment]
Hi @fmadani, 

As mentioned, this repo is more for general PRS tutorial and are not specific to LDpred2. For LDpred2 supports, I suggest you to ask the questions in: https://github.com/privefl/bigsnpr/issues

Thanks

**Comment by privefl** [comment]
Please stop opening issues here.
If you have questions about LDpred2, open them at https://github.com/privefl/bigsnpr/issues.
Also, please have a look at the LDpred2 tutorial (https://privefl.github.io/bigsnpr/articles/LDpred2.html), where you'll find the answer to your question.

**Comment by fmadani** [comment]
OK. I will open in bigsnpr, but please note LDPred-2 is part of the tutorial as well, and I am literally practicing the tutorial. I am not practicing bigsnpr.
