### ISSUE TITLE
No application for fam variable  in the Lassosum

### ISSUE THREAD

**Issue by fmadani** [choishingwan/PRS-Tutorial#39]
Hi @choishingwan 

In the Lassosum, fam variable is generated through these codes:

fam <- fread(paste0(bfile, ".fam"))
fam[,ID:=do.call(paste, c(.SD, sep=":")),.SDcols=c(1:2)]

but, there is no usage for 'fam' in the lassosum. Please clarify

Thank you,
Farshad

**Comment by choishingwan** [comment]
Right, unless you are doing sample filtering, you can ignore that. I forgot
to remove it from the script as this was originally an excerpt from my
lassosum script that was used for other analyses

**Comment by fmadani** [comment]
Thank you Sam for the clarification
