### ISSUE TITLE
Question on PRS.summary file

### ISSUE THREAD

**Issue by dzimmerman-amc** [choishingwan/PRS-Tutorial#41]
Hi there,

I just wanted to ask how PRSice chooses the best model fit in the .summary file. I am using a binary trait and it seems to choose the the threshold of 1 is best fit with all of my SNPs inlcuded. Additionally, is it possible to get the list of actual SNPs that are included under the Num_SNP column.

Thanks in advance!

Best wishes,
Dominic

**Comment by choishingwan** [comment]
We just did a regression and find one resulting in highest R2.

use --print-snp to get the list
