### ISSUE TITLE
Query regarding PRS

### ISSUE THREAD

**Issue by singh-p** [choishingwan/PRS-Tutorial#43]
Hi Shing Wan Choi

We have been using your Polygenic risk score analysis (https://choishingwan.github.io/PRS-Tutorial/ldpred/). We could run all the scripts successfully however we are unable to interpret the results appropriately. I will brief you about my project, we are working on a case-control GWAS analysis between a neuro-psychiatric disease and compared it with healthy controls. The cohort includes the Indian population.  On filtering out HAMPMAP SNPs using

sumstats <- sumstats[sumstats$rsid%in% info$rsid,]
we retrieved 719204 observations of 12 variables

Later, on comparing base and target data, 
info_snp <- snp_match(sumstats, map, match.min.prop=0.1)
we retrieved 74,513 SNPs.

The h2_est value was 0.002

The genetic heritability of our disease of interest is ~30-40%. But our h2_est value is so low. Is it because our base data and target data belongs to two different populations? (base data- European, Target data- Indian) or Because we do not have enough comparable snps between our data and hapmap? or any other reasons?

With such low h2-est values, can we still proceed with PRS?
Also, for case-control analysis, do we follow linear or logistic model?

We performed our analysis on ~400 cases and 400 controls and screened ~4 lakh markers.

**Comment by choishingwan** [comment]
Low h2 means your base data likely does not have enough power. If data is from two different population, it will be more difficult to carry out the PRS analyses (see the literature)
