### ISSUE TITLE
Missing Height.QC.gz file

### ISSUE THREAD

**Issue by jzollner** [choishingwan/PRS-Tutorial#44]
Dear Shing Wan Choi, 
I am completing the PRS-Tutorial. 
Currently at step:
QC of target data
# Mismatching SNPs

In the R code it mentions this: height <- fread("**Height.QC.gz**"). 

I don't seem to have created that file (Height.QC.gz) in the previous steps. I have these other files:
 EUR.QC.fam, EUR.QC.het, EUR.QC.hh, EUR.QC.irem, EUR.QC.log, EUR.QC.prune.in, EUR.QC.prune.out, EUR.QC.snplist

I only have EUR.height
When I change height <- fread("**EUR.height**") then i get a final error saying that:
Error in toupper(Height$A1) : object 'Height' not found
> Height$A2 <- toupper(Height$A2)
Error in toupper(Height$A2) : object 'Height' not found

Would you be able to help what I have done wrong? Many thanks,
Julia

**Comment by choishingwan** [comment]
You should be able to find that if you go through the summary statistic
quality control section

**Comment by jzollner** [comment]
Found it, amazing. Thank you so much!
