### ISSUE TITLE
Base Data QC, no INFO score?

### ISSUE THREAD

**Issue by Poppo9** [choishingwan/PRS-Tutorial#45]
I'm having some problems finding the imputation (INFO) score column in my GWAS base data. 
I found the GWAS base data (study GCST90027158) from the GWAS Catalog ( https://www.ebi.ac.uk/gwas/home ). The file I downlaoded contains every other information needed for quality control exept for the INFO score. What can I do?
Has the imputation score already been accounted for before uploading the data on the catalog? How can I find information about this? Has imputation already been conducted or it's up to me to do it?
Thanks in advance

**Comment by choishingwan** [comment]
You might need to read their paper. But it does seems like it is an imputed data. If the INFO is not available, you can still use the sumstat, just keep in mind some of the variants might be low quality
