### ISSUE TITLE
Not getting any plot

### ISSUE THREAD

**Issue by SoumenMaity922** [choishingwan/PRS-Tutorial#52]
Hi,
I follow all the steps described in the tutorial session. I downloaded the data(base and target) at the beginning of QC ( didn't download the QC data). I have run the following code 
PRSice --base Height.QC.gz --target EUR.QC --binary-target F --pheno EUR.height --cov EUR.covariate --base-maf MAF:0.01 --base-info INFO:0.8 --stat OR --or --out EUR 
It creates three files EUR.best, EUR.prsice, and EUR.summary. But it doesn't create any plot.  Why? Any help?
I am using the HPC environment and it uses the PRSice-2.3.5 version.

**Comment by choishingwan** [comment]
The PRSice executable itself does not generate plot. For plot generation, you need to use PRSice.R which is a wrapper of PRSice.
