### ISSUE TITLE
Confusion about pruning and clumping

### ISSUE THREAD

**Issue by ptranvan** [choishingwan/PRS-Tutorial#53]
In the PRS Plink section, there is a clumping step, but I thought we already had a set of uncorrelated SNPs because in the QC of target data section, we had performed a pruning step.

So, I am confused about why there is a clumping step after pruning. I thought it was either one or the other, but can we actually perform both steps together?

**Comment by choishingwan** [comment]
prunning was done for QC, mainly for sex check and heterozygous analyses. We would not thin down the genotype file based on the pruned SNPs for subsequent analyses.

For the actual PRS calculation, the full genotype were used, and clumping was then done to extract the most significant SNPs within the region.
