### ISSUE TITLE
a1/a0 in genotype file using the LDpred2 tutorial

### ISSUE THREAD

**Issue by kaibios0101** [choishingwan/PRS-Tutorial#8]
Hi, Shing Wan. LDpred2 is an wonderful tool for PRS.  Thanks! I just found an inconsistency way of naming the a1/a0 in genotype file when extracting the SNP information from the genotype.

In your tutorial, you name the A1 of bim file as the a1 (corresponding to effect allele in GWAS summary datasets) and A2 as the a0, shown as:

## extract the SNP information from the genotype
map <- obj.bigSNP$map[-2]
names(map) <- c("chr", "rsid", "pos", "a1", "a0")
link: [https://choishingwan.github.io/PRS-Tutorial/ldpred/](url)

However, I found the code for preparing sumstats in your new paper (LDpred2: better, faster, stronger). In this part, you name A1 of bim file as the a0 and A2 as the a1, shown as:

ukb <- snp_attach("data/UKBB_imp_HM3.rds")
G <- ukb$genotypes
map <- transmute(ukb$map,
                 chr = as.integer(chromosome), pos = physical.pos,
                 a0 = allele1, a1 = allele2)  # reversed somehow..
link: [https://github.com/privefl/paper-ldpred2/blob/master/code/prepare-sumstats.R](url)

I'm not sure which is correct. This inconsistency may affect the estimation of effect size and heritability.  Thus, maybe you need to recheck it? Many thank!

Best!

**Comment by choishingwan** [comment]
Hi Kaibios,

Unfortunately, I am not the author of LDpred2. You might want to direct
your question to them instead https://github.com/privefl/bigsnpr/. Though
from my understanding, the A1 allele should be the effective allele and in
our simulation, the A1 in the bim file is our effective allele. That's the
reason why we use A1 as A1 if that make sense.

Sam

**Comment by kaibios0101** [comment]
Thanks for your answer. Much help! 

kai
